### ISSUE TITLE
Crash on the boss of the first floor.

### ISSUE THREAD

**Issue by Vlad-00003** [GraysonnG/BlackMageMod#1]
This char is pretty awsome!
but still hard to play tho.... maybe I'm doing something wrong, but I've spend much attempts trying to kill Hexaghost. At the end I just gave up and give myself almost infinite hp.
And there goes that moment - the enemy is down. 
And the game crashes =D Even if he is being killed by the console.

Some information:
Version - steam latest, main branch, from 03-22-2018.
ModTheSpire v2.5.0
BaseMod v2.3.0
and this mod - v0.0.2
Deck
+ IceStrike x2
+ Fire Strike x3
+ Defend x3
+ Defend+ x2
+ Conversion+
+ Fire Blast x2
+ Firestorm x2
+ Shadow Strike
+ Swiftcast
+ Flame Wall
+ Mage's Song
+ Parasite
+ Blizzard

*I don't actually think that is has something to do with a deck, but still ¯\\_(ツ)_/¯*

```21:25:44.095 INFO basemod.BaseMod> powers modified
21:26:42.080 INFO helpers.FileSaver> Save Succeeded: preferences\BLACK_MAGE_CLASS
21:26:42.083 INFO helpers.FileSaver> Save Succeeded: preferences\BLACK_MAGE_CLASS
21:26:42.085 INFO helpers.FileSaver> Save Succeeded: preferences\STSUnlocks
21:26:42.085 INFO unlock.UnlockTracker> Hard Unlock: GHOST
21:26:43.593 INFO basemod.BaseMod> publish post combat
21:26:43.854 INFO rooms.AbstractRoom> POTION CHANCE: 50
Exception: java.lang.IllegalArgumentException: n must be positive
21:26:43.856 ERROR core.CardCrawlGame> Exception caught
java.lang.IllegalArgumentException: n must be positive
	at com.badlogic.gdx.math.RandomXS128.nextLong(RandomXS128.java:110) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.math.RandomXS128.nextInt(RandomXS128.java:99) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.random.Random.random(Random.java:52) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.cards.CardGroup.getRandomCard(CardGroup.java:545) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.getCard(AbstractDungeon.java:1872) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.getRewardCards(AbstractDungeon.java:1797) ~[?:?]
	at com.megacrit.cardcrawl.rewards.RewardItem.<init>(RewardItem.java:126) ~[?:?]
	at com.megacrit.cardcrawl.screens.CombatRewardScreen.setupItemReward(CombatRewardScreen.java:88) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.screens.CombatRewardScreen.open(CombatRewardScreen.java:319) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:342) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2439) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:790) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:374) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Game closed.```

**Comment by Vlad-00003** [comment]
I'm not a java type, so I actually don't wanna dig deeper myself =)

**Comment by Vlad-00003** [comment]
Oh, and also - Fire wall description doesn't says that it's also depends on the current Fire level....

**Comment by GraysonnG** [comment]
This issue has been fixed in the latest build, I will make a release with the fix tonight.
